sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js:
  - "8"
before_install:
  - npm i npm@^5 -g
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
install:
  - npm install
before_script:
  - npm prune
script:
  - npm test
  - npm run semantic-release-pre
  - npm run build
after_success:
  - npm run publish-npm
  - npm run semantic-release-post
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run build-docs && npm run publish-docs
  - npm run report-coverage
notifications:
  email: false
